# Generated by Django 5.2.5 on 2025-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("transfer", "Оплата по счету"), ("cash", "Оплата наличными")],
                default="transfer",
                help_text="Укажите вид оплаты",
                max_length=10,
                verbose_name="Вид оплаты",
            ),
        ),
    ]
