# Generated by Django 5.2.5 on 2025-09-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update_course",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Укажите дату последнего обновления курса",
                verbose_name="Дата последнего обновления курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="last_update_lesson",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Укажите дату последнего обновления курса",
                verbose_name="Дата последнего обновления курса",
            ),
        ),
    ]
