# Generated by Django 5.2.5 on 2025-09-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_last_update_course_lesson_last_update_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Укажите статус подписки",
                null=True,
                verbose_name="Статус подписки",
            ),
        ),
    ]
